INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES (3, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 8);
INSERT INTO users (name, age) VALUES (Margot, 27);
INSERT INTO users (name, age) VALUES (Brian, 27);
INSERT INTO users (name, age) VALUES (Adam, 27);
INSERT INTO users (name, age) VALUES (Margot, 27);
INSERT INTO users (name, age) VALUES (Brian, 27);
INSERT INTO users (name, age) VALUES (Adam, 27);
INSERT INTO users (name, age) VALUES (Margot, 27);
INSERT INTO users (name, age) VALUES (Brian, 27);
INSERT INTO users (name, age) VALUES (Adam, 27);
INSERT INTO users (name, age) VALUES (Margot, 27);
INSERT INTO users (name, age) VALUES (Brian, 27);
INSERT INTO users (name, age) VALUES (Adam, 27);
INSERT INTO users (name, age) VALUES (Margot, 27);
INSERT INTO users (name, age) VALUES (Brian, 27);
INSERT INTO users (name, age) VALUES (Adam, 27);
INSERT INTO users (name, age) VALUES (Margot, 27);
INSERT INTO users (name, age) VALUES (Brian, 27);
INSERT INTO users (name, age) VALUES (Adam, 27);
INSERT INTO users (name, age) VALUES (Margot, 27);
INSERT INTO users (name, age) VALUES (Brian, 27);