INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Test", "Test", 100, "Jan_5", "Jan_10");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Test", "Test", 100, "Jan_5", "Jan_10");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Test", "Test", 100, "Jan_5", "Jan_10");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Test", "Test", 100, "Jan_5", "Jan_10");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Test", "Test", 100, "Jan_5", "Jan_10");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Test", "Test", 100, "Jan_5", "Jan_10");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Test", "Test", 100, "Jan_5", "Jan_10");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Test", "Test", 100, "Jan_5", "Jan_10");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Test", "Test", 100, "Jan_5", "Jan_10");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Test", "Test", 100, "Jan_5", "Jan_10");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Test", "Test", 100, "Jan_5", "Jan_10");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Test", "Test", 100, "Jan_5", "Jan_10");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Test", "Test", 100, "Jan_5", "Jan_10");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Test", "Test", 100, "Jan_5", "Jan_10");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Test", "Test", 100, "Jan_5", "Jan_10");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Test", "Test", 100, "Jan_5", "Jan_10");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Test", "Test", 100, "Jan_5", "Jan_10");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Test", "Test", 100, "Jan_5", "Jan_10");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Test", "Test", 100, "Jan_5", "Jan_10");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Test", "Test", 100, "Jan_5", "Jan_10");



INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 8);
INSERT INTO users (name, age) VALUES ("Margot", 27);
